[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "purple-mri"
authors = [{name = "Pulkit Khandelwal", email = "pkhandelwal1@mgh.harvard.edu"}]
dynamic = ["version", "description"]
